var _advanced_local_faction_placement_handler_editor_8cs =
[
    [ "AdvancedLocalFactionPlacementHandlerEditor", "d9/df5/class_r_t_s_engine_1_1_editor_only_1_1_building_extension_1_1_advanced_local_faction_placement_handler_editor.html", "d9/df5/class_r_t_s_engine_1_1_editor_only_1_1_building_extension_1_1_advanced_local_faction_placement_handler_editor" ]
];