var namespace_r_t_s_engine_1_1_editor_only_1_1_building_extension =
[
    [ "AdvancedBuildingPlacerEditor", "d8/d91/class_r_t_s_engine_1_1_editor_only_1_1_building_extension_1_1_advanced_building_placer_editor.html", "d8/d91/class_r_t_s_engine_1_1_editor_only_1_1_building_extension_1_1_advanced_building_placer_editor" ],
    [ "AdvancedLocalFactionPlacementHandlerEditor", "d9/df5/class_r_t_s_engine_1_1_editor_only_1_1_building_extension_1_1_advanced_local_faction_placement_handler_editor.html", "d9/df5/class_r_t_s_engine_1_1_editor_only_1_1_building_extension_1_1_advanced_local_faction_placement_handler_editor" ],
    [ "BuildingPlacementEditor", "df/d02/class_r_t_s_engine_1_1_editor_only_1_1_building_extension_1_1_building_placement_editor.html", "df/d02/class_r_t_s_engine_1_1_editor_only_1_1_building_extension_1_1_building_placement_editor" ]
];