var _n_p_c_faction_entity_force_creation_data_8cs =
[
    [ "NPCFactionEntityForceCreationData", "struct_r_t_s_engine_1_1_n_p_c_1_1_unit_extension_1_1_n_p_c_faction_entity_force_creation_data.html", "struct_r_t_s_engine_1_1_n_p_c_1_1_unit_extension_1_1_n_p_c_faction_entity_force_creation_data" ]
];