var _n_p_c_resource_type_collection_data_8cs =
[
    [ "NPCResourceTypeCollectionData", "struct_r_t_s_engine_1_1_n_p_c_1_1_resource_extension_1_1_n_p_c_resource_type_collection_data.html", "struct_r_t_s_engine_1_1_n_p_c_1_1_resource_extension_1_1_n_p_c_resource_type_collection_data" ]
];