var _n_p_c_territory_defense_engage_event_args_8cs =
[
    [ "NPCTerritoryDefenseEngageEventArgs", "class_r_t_s_engine_1_1_n_p_c_1_1_event_1_1_n_p_c_territory_defense_engage_event_args.html", "class_r_t_s_engine_1_1_n_p_c_1_1_event_1_1_n_p_c_territory_defense_engage_event_args" ]
];