var namespace_r_t_s_engine_1_1_minimap_1_1_notification =
[
    [ "AttackMinimapNotificationManager", "class_r_t_s_engine_1_1_minimap_1_1_notification_1_1_attack_minimap_notification_manager.html", "class_r_t_s_engine_1_1_minimap_1_1_notification_1_1_attack_minimap_notification_manager" ],
    [ "IAttackMinimapNotificationManager", "interface_r_t_s_engine_1_1_minimap_1_1_notification_1_1_i_attack_minimap_notification_manager.html", "interface_r_t_s_engine_1_1_minimap_1_1_notification_1_1_i_attack_minimap_notification_manager" ]
];