var namespace_r_t_s_engine_1_1_editor_only_1_1_n_p_c_1_1_attack =
[
    [ "NPCAttackManagerEditor", "class_r_t_s_engine_1_1_editor_only_1_1_n_p_c_1_1_attack_1_1_n_p_c_attack_manager_editor.html", "class_r_t_s_engine_1_1_editor_only_1_1_n_p_c_1_1_attack_1_1_n_p_c_attack_manager_editor" ],
    [ "NPCDefenseManagerEditor", "class_r_t_s_engine_1_1_editor_only_1_1_n_p_c_1_1_attack_1_1_n_p_c_defense_manager_editor.html", "class_r_t_s_engine_1_1_editor_only_1_1_n_p_c_1_1_attack_1_1_n_p_c_defense_manager_editor" ]
];