var namespace_r_t_s_engine_1_1_building_extension =
[
    [ "AdvancedBuildingPlacementHandlerBase", "class_r_t_s_engine_1_1_building_extension_1_1_advanced_building_placement_handler_base.html", "class_r_t_s_engine_1_1_building_extension_1_1_advanced_building_placement_handler_base" ],
    [ "AdvancedBuildingPlacer", "class_r_t_s_engine_1_1_building_extension_1_1_advanced_building_placer.html", "class_r_t_s_engine_1_1_building_extension_1_1_advanced_building_placer" ],
    [ "AdvancedLocalFactionPlacementHandler", "class_r_t_s_engine_1_1_building_extension_1_1_advanced_local_faction_placement_handler.html", "class_r_t_s_engine_1_1_building_extension_1_1_advanced_local_faction_placement_handler" ],
    [ "AdvancedPendingPlacementData", "struct_r_t_s_engine_1_1_building_extension_1_1_advanced_pending_placement_data.html", "struct_r_t_s_engine_1_1_building_extension_1_1_advanced_pending_placement_data" ],
    [ "Border", "class_r_t_s_engine_1_1_building_extension_1_1_border.html", "class_r_t_s_engine_1_1_building_extension_1_1_border" ],
    [ "BorderMinimapUIObject", "class_r_t_s_engine_1_1_building_extension_1_1_border_minimap_u_i_object.html", "class_r_t_s_engine_1_1_building_extension_1_1_border_minimap_u_i_object" ],
    [ "BorderObject", "class_r_t_s_engine_1_1_building_extension_1_1_border_object.html", "class_r_t_s_engine_1_1_building_extension_1_1_border_object" ],
    [ "BorderObjectSpawnInput", "class_r_t_s_engine_1_1_building_extension_1_1_border_object_spawn_input.html", "class_r_t_s_engine_1_1_building_extension_1_1_border_object_spawn_input" ],
    [ "BuildingAmount", "struct_r_t_s_engine_1_1_building_extension_1_1_building_amount.html", "struct_r_t_s_engine_1_1_building_extension_1_1_building_amount" ],
    [ "BuildingGateHandler", "class_r_t_s_engine_1_1_building_extension_1_1_building_gate_handler.html", "class_r_t_s_engine_1_1_building_extension_1_1_building_gate_handler" ],
    [ "BuildingManager", "class_r_t_s_engine_1_1_building_extension_1_1_building_manager.html", "class_r_t_s_engine_1_1_building_extension_1_1_building_manager" ],
    [ "BuildingPlaceAroundCondition", "class_r_t_s_engine_1_1_building_extension_1_1_building_place_around_condition.html", "class_r_t_s_engine_1_1_building_extension_1_1_building_place_around_condition" ],
    [ "BuildingPlaceAroundData", "struct_r_t_s_engine_1_1_building_extension_1_1_building_place_around_data.html", "struct_r_t_s_engine_1_1_building_extension_1_1_building_place_around_data" ],
    [ "BuildingPlaceAroundHandler", "class_r_t_s_engine_1_1_building_extension_1_1_building_place_around_handler.html", "class_r_t_s_engine_1_1_building_extension_1_1_building_place_around_handler" ],
    [ "BuildingPlacedData", "struct_r_t_s_engine_1_1_building_extension_1_1_building_placed_data.html", "struct_r_t_s_engine_1_1_building_extension_1_1_building_placed_data" ],
    [ "BuildingPlacement", "class_r_t_s_engine_1_1_building_extension_1_1_building_placement.html", "class_r_t_s_engine_1_1_building_extension_1_1_building_placement" ],
    [ "BuildingPlacementGridData", "struct_r_t_s_engine_1_1_building_extension_1_1_building_placement_grid_data.html", "struct_r_t_s_engine_1_1_building_extension_1_1_building_placement_grid_data" ],
    [ "BuildingPlacementHandlerBase", "class_r_t_s_engine_1_1_building_extension_1_1_building_placement_handler_base.html", "class_r_t_s_engine_1_1_building_extension_1_1_building_placement_handler_base" ],
    [ "BuildingPlacementHandlerMonoBehaviourBase", "class_r_t_s_engine_1_1_building_extension_1_1_building_placement_handler_mono_behaviour_base.html", "class_r_t_s_engine_1_1_building_extension_1_1_building_placement_handler_mono_behaviour_base" ],
    [ "BuildingPlacementOptions", "struct_r_t_s_engine_1_1_building_extension_1_1_building_placement_options.html", "struct_r_t_s_engine_1_1_building_extension_1_1_building_placement_options" ],
    [ "BuildingPlacementSegmentData", "struct_r_t_s_engine_1_1_building_extension_1_1_building_placement_segment_data.html", "struct_r_t_s_engine_1_1_building_extension_1_1_building_placement_segment_data" ],
    [ "BuildingPlacementTask", "class_r_t_s_engine_1_1_building_extension_1_1_building_placement_task.html", "class_r_t_s_engine_1_1_building_extension_1_1_building_placement_task" ],
    [ "BuildingPlacementUpdateData", "struct_r_t_s_engine_1_1_building_extension_1_1_building_placement_update_data.html", "struct_r_t_s_engine_1_1_building_extension_1_1_building_placement_update_data" ],
    [ "BuildingPlacer", "class_r_t_s_engine_1_1_building_extension_1_1_building_placer.html", "class_r_t_s_engine_1_1_building_extension_1_1_building_placer" ],
    [ "BuildingPlacerRallypointCondition", "class_r_t_s_engine_1_1_building_extension_1_1_building_placer_rallypoint_condition.html", "class_r_t_s_engine_1_1_building_extension_1_1_building_placer_rallypoint_condition" ],
    [ "CompletedPlacementData", "struct_r_t_s_engine_1_1_building_extension_1_1_completed_placement_data.html", "struct_r_t_s_engine_1_1_building_extension_1_1_completed_placement_data" ],
    [ "FactionEntitySeller", "class_r_t_s_engine_1_1_building_extension_1_1_faction_entity_seller.html", "class_r_t_s_engine_1_1_building_extension_1_1_faction_entity_seller" ],
    [ "GlobalGridPlacementMesh", "class_r_t_s_engine_1_1_building_extension_1_1_global_grid_placement_mesh.html", "class_r_t_s_engine_1_1_building_extension_1_1_global_grid_placement_mesh" ],
    [ "GridPlacementHandler", "class_r_t_s_engine_1_1_building_extension_1_1_grid_placement_handler.html", "class_r_t_s_engine_1_1_building_extension_1_1_grid_placement_handler" ],
    [ "IBorder", "interface_r_t_s_engine_1_1_building_extension_1_1_i_border.html", "interface_r_t_s_engine_1_1_building_extension_1_1_i_border" ],
    [ "IBorderObject", "interface_r_t_s_engine_1_1_building_extension_1_1_i_border_object.html", "interface_r_t_s_engine_1_1_building_extension_1_1_i_border_object" ],
    [ "IBuildingGateHandler", "interface_r_t_s_engine_1_1_building_extension_1_1_i_building_gate_handler.html", "interface_r_t_s_engine_1_1_building_extension_1_1_i_building_gate_handler" ],
    [ "IBuildingManager", "interface_r_t_s_engine_1_1_building_extension_1_1_i_building_manager.html", "interface_r_t_s_engine_1_1_building_extension_1_1_i_building_manager" ],
    [ "IBuildingPlacement", "interface_r_t_s_engine_1_1_building_extension_1_1_i_building_placement.html", "interface_r_t_s_engine_1_1_building_extension_1_1_i_building_placement" ],
    [ "IBuildingPlacementHandler", "interface_r_t_s_engine_1_1_building_extension_1_1_i_building_placement_handler.html", "interface_r_t_s_engine_1_1_building_extension_1_1_i_building_placement_handler" ],
    [ "IBuildingPlacementTask", "interface_r_t_s_engine_1_1_building_extension_1_1_i_building_placement_task.html", "interface_r_t_s_engine_1_1_building_extension_1_1_i_building_placement_task" ],
    [ "IBuildingPlacer", "interface_r_t_s_engine_1_1_building_extension_1_1_i_building_placer.html", "interface_r_t_s_engine_1_1_building_extension_1_1_i_building_placer" ],
    [ "IBuildingPlacerCondition", "interface_r_t_s_engine_1_1_building_extension_1_1_i_building_placer_condition.html", "interface_r_t_s_engine_1_1_building_extension_1_1_i_building_placer_condition" ],
    [ "IGridPlacementHandler", "interface_r_t_s_engine_1_1_building_extension_1_1_i_grid_placement_handler.html", "interface_r_t_s_engine_1_1_building_extension_1_1_i_grid_placement_handler" ],
    [ "IGridPlacementMesh", "interface_r_t_s_engine_1_1_building_extension_1_1_i_grid_placement_mesh.html", "interface_r_t_s_engine_1_1_building_extension_1_1_i_grid_placement_mesh" ],
    [ "IPendingPlacementData", "interface_r_t_s_engine_1_1_building_extension_1_1_i_pending_placement_data.html", "interface_r_t_s_engine_1_1_building_extension_1_1_i_pending_placement_data" ],
    [ "LocalFactionPlacementHandler", "class_r_t_s_engine_1_1_building_extension_1_1_local_faction_placement_handler.html", "class_r_t_s_engine_1_1_building_extension_1_1_local_faction_placement_handler" ],
    [ "LocalGridPlacementMesh", "class_r_t_s_engine_1_1_building_extension_1_1_local_grid_placement_mesh.html", "class_r_t_s_engine_1_1_building_extension_1_1_local_grid_placement_mesh" ],
    [ "PendingPlacementData", "struct_r_t_s_engine_1_1_building_extension_1_1_pending_placement_data.html", "struct_r_t_s_engine_1_1_building_extension_1_1_pending_placement_data" ],
    [ "PlacementGridCell", "class_r_t_s_engine_1_1_building_extension_1_1_placement_grid_cell.html", "class_r_t_s_engine_1_1_building_extension_1_1_placement_grid_cell" ],
    [ "ConstructionType", "namespace_r_t_s_engine_1_1_building_extension.html#a82956cd4157adb1fe21740498c8ebb53", [
      [ "health", "namespace_r_t_s_engine_1_1_building_extension.html#a82956cd4157adb1fe21740498c8ebb53a555bf8344ca0caf09b42f55e185526d8", null ],
      [ "time", "namespace_r_t_s_engine_1_1_building_extension.html#a82956cd4157adb1fe21740498c8ebb53a07cc694b9b3fc636710fa08b6922c42b", null ]
    ] ],
    [ "GridAreaPivotPoint", "namespace_r_t_s_engine_1_1_building_extension.html#aa5965fe02cd6f393f113e49aee35279a", [
      [ "center", "namespace_r_t_s_engine_1_1_building_extension.html#aa5965fe02cd6f393f113e49aee35279aaadb115059e28d960fa8badfac5516667", null ],
      [ "topLeft", "namespace_r_t_s_engine_1_1_building_extension.html#aa5965fe02cd6f393f113e49aee35279aa79ad18f72445fe00af22637f175bf878", null ],
      [ "bottomLeft", "namespace_r_t_s_engine_1_1_building_extension.html#aa5965fe02cd6f393f113e49aee35279aa5d42a1b01d408cdd65bb03d50fa0dd22", null ],
      [ "topRight", "namespace_r_t_s_engine_1_1_building_extension.html#aa5965fe02cd6f393f113e49aee35279aa3dc32cc133f011c0f50bca1a9b09e7a1", null ],
      [ "bottomRight", "namespace_r_t_s_engine_1_1_building_extension.html#aa5965fe02cd6f393f113e49aee35279aa83da849839b8af951893682450a363a1", null ]
    ] ]
];