var namespace_r_t_s_engine_1_1_save_1_1_game_1_1_entity_component =
[
    [ "ISavableEntityComponent", "interface_r_t_s_engine_1_1_save_1_1_game_1_1_entity_component_1_1_i_savable_entity_component.html", "interface_r_t_s_engine_1_1_save_1_1_game_1_1_entity_component_1_1_i_savable_entity_component" ]
];