var namespace_r_t_s_engine_1_1_building_extension =
[
    [ "AdvancedBuildingPlacementHandlerBase", "dc/d73/class_r_t_s_engine_1_1_building_extension_1_1_advanced_building_placement_handler_base.html", "dc/d73/class_r_t_s_engine_1_1_building_extension_1_1_advanced_building_placement_handler_base" ],
    [ "AdvancedBuildingPlacer", "d5/d6b/class_r_t_s_engine_1_1_building_extension_1_1_advanced_building_placer.html", "d5/d6b/class_r_t_s_engine_1_1_building_extension_1_1_advanced_building_placer" ],
    [ "AdvancedLocalFactionPlacementHandler", "de/dad/class_r_t_s_engine_1_1_building_extension_1_1_advanced_local_faction_placement_handler.html", "de/dad/class_r_t_s_engine_1_1_building_extension_1_1_advanced_local_faction_placement_handler" ],
    [ "AdvancedPendingPlacementData", "dd/d8c/struct_r_t_s_engine_1_1_building_extension_1_1_advanced_pending_placement_data.html", "dd/d8c/struct_r_t_s_engine_1_1_building_extension_1_1_advanced_pending_placement_data" ],
    [ "Border", "d2/dc4/class_r_t_s_engine_1_1_building_extension_1_1_border.html", "d2/dc4/class_r_t_s_engine_1_1_building_extension_1_1_border" ],
    [ "BorderMinimapUIObject", "d4/de3/class_r_t_s_engine_1_1_building_extension_1_1_border_minimap_u_i_object.html", "d4/de3/class_r_t_s_engine_1_1_building_extension_1_1_border_minimap_u_i_object" ],
    [ "BorderObject", "d4/d5d/class_r_t_s_engine_1_1_building_extension_1_1_border_object.html", "d4/d5d/class_r_t_s_engine_1_1_building_extension_1_1_border_object" ],
    [ "BorderObjectSpawnInput", "dd/da4/class_r_t_s_engine_1_1_building_extension_1_1_border_object_spawn_input.html", "dd/da4/class_r_t_s_engine_1_1_building_extension_1_1_border_object_spawn_input" ],
    [ "BuildingAmount", "d0/d9b/struct_r_t_s_engine_1_1_building_extension_1_1_building_amount.html", "d0/d9b/struct_r_t_s_engine_1_1_building_extension_1_1_building_amount" ],
    [ "BuildingGateHandler", "d3/ded/class_r_t_s_engine_1_1_building_extension_1_1_building_gate_handler.html", "d3/ded/class_r_t_s_engine_1_1_building_extension_1_1_building_gate_handler" ],
    [ "BuildingManager", "da/d4f/class_r_t_s_engine_1_1_building_extension_1_1_building_manager.html", "da/d4f/class_r_t_s_engine_1_1_building_extension_1_1_building_manager" ],
    [ "BuildingPlaceAroundCondition", "d5/d71/class_r_t_s_engine_1_1_building_extension_1_1_building_place_around_condition.html", "d5/d71/class_r_t_s_engine_1_1_building_extension_1_1_building_place_around_condition" ],
    [ "BuildingPlaceAroundData", "d0/d38/struct_r_t_s_engine_1_1_building_extension_1_1_building_place_around_data.html", "d0/d38/struct_r_t_s_engine_1_1_building_extension_1_1_building_place_around_data" ],
    [ "BuildingPlaceAroundHandler", "d4/d29/class_r_t_s_engine_1_1_building_extension_1_1_building_place_around_handler.html", "d4/d29/class_r_t_s_engine_1_1_building_extension_1_1_building_place_around_handler" ],
    [ "BuildingPlacedData", "db/d45/struct_r_t_s_engine_1_1_building_extension_1_1_building_placed_data.html", "db/d45/struct_r_t_s_engine_1_1_building_extension_1_1_building_placed_data" ],
    [ "BuildingPlacement", "dc/deb/class_r_t_s_engine_1_1_building_extension_1_1_building_placement.html", "dc/deb/class_r_t_s_engine_1_1_building_extension_1_1_building_placement" ],
    [ "BuildingPlacementGridData", "d6/d0d/struct_r_t_s_engine_1_1_building_extension_1_1_building_placement_grid_data.html", "d6/d0d/struct_r_t_s_engine_1_1_building_extension_1_1_building_placement_grid_data" ],
    [ "BuildingPlacementHandlerBase", "d3/d93/class_r_t_s_engine_1_1_building_extension_1_1_building_placement_handler_base.html", "d3/d93/class_r_t_s_engine_1_1_building_extension_1_1_building_placement_handler_base" ],
    [ "BuildingPlacementHandlerMonoBehaviourBase", "d4/dc4/class_r_t_s_engine_1_1_building_extension_1_1_building_placement_handler_mono_behaviour_base.html", "d4/dc4/class_r_t_s_engine_1_1_building_extension_1_1_building_placement_handler_mono_behaviour_base" ],
    [ "BuildingPlacementOptions", "df/d8c/struct_r_t_s_engine_1_1_building_extension_1_1_building_placement_options.html", "df/d8c/struct_r_t_s_engine_1_1_building_extension_1_1_building_placement_options" ],
    [ "BuildingPlacementSegmentData", "d0/d87/struct_r_t_s_engine_1_1_building_extension_1_1_building_placement_segment_data.html", "d0/d87/struct_r_t_s_engine_1_1_building_extension_1_1_building_placement_segment_data" ],
    [ "BuildingPlacementTask", "d7/d70/class_r_t_s_engine_1_1_building_extension_1_1_building_placement_task.html", "d7/d70/class_r_t_s_engine_1_1_building_extension_1_1_building_placement_task" ],
    [ "BuildingPlacementUpdateData", "d8/d83/struct_r_t_s_engine_1_1_building_extension_1_1_building_placement_update_data.html", "d8/d83/struct_r_t_s_engine_1_1_building_extension_1_1_building_placement_update_data" ],
    [ "BuildingPlacer", "dc/d2e/class_r_t_s_engine_1_1_building_extension_1_1_building_placer.html", "dc/d2e/class_r_t_s_engine_1_1_building_extension_1_1_building_placer" ],
    [ "BuildingPlacerRallypointCondition", "db/d25/class_r_t_s_engine_1_1_building_extension_1_1_building_placer_rallypoint_condition.html", "db/d25/class_r_t_s_engine_1_1_building_extension_1_1_building_placer_rallypoint_condition" ],
    [ "CompletedPlacementData", "dd/dc3/struct_r_t_s_engine_1_1_building_extension_1_1_completed_placement_data.html", "dd/dc3/struct_r_t_s_engine_1_1_building_extension_1_1_completed_placement_data" ],
    [ "FactionEntitySeller", "d2/ddc/class_r_t_s_engine_1_1_building_extension_1_1_faction_entity_seller.html", "d2/ddc/class_r_t_s_engine_1_1_building_extension_1_1_faction_entity_seller" ],
    [ "GlobalGridPlacementMesh", "d5/d7d/class_r_t_s_engine_1_1_building_extension_1_1_global_grid_placement_mesh.html", "d5/d7d/class_r_t_s_engine_1_1_building_extension_1_1_global_grid_placement_mesh" ],
    [ "GridPlacementHandler", "d0/da6/class_r_t_s_engine_1_1_building_extension_1_1_grid_placement_handler.html", "d0/da6/class_r_t_s_engine_1_1_building_extension_1_1_grid_placement_handler" ],
    [ "IBorder", "d5/dd0/interface_r_t_s_engine_1_1_building_extension_1_1_i_border.html", "d5/dd0/interface_r_t_s_engine_1_1_building_extension_1_1_i_border" ],
    [ "IBorderObject", "db/d62/interface_r_t_s_engine_1_1_building_extension_1_1_i_border_object.html", "db/d62/interface_r_t_s_engine_1_1_building_extension_1_1_i_border_object" ],
    [ "IBuildingGateHandler", "df/d44/interface_r_t_s_engine_1_1_building_extension_1_1_i_building_gate_handler.html", "df/d44/interface_r_t_s_engine_1_1_building_extension_1_1_i_building_gate_handler" ],
    [ "IBuildingManager", "d3/d65/interface_r_t_s_engine_1_1_building_extension_1_1_i_building_manager.html", "d3/d65/interface_r_t_s_engine_1_1_building_extension_1_1_i_building_manager" ],
    [ "IBuildingPlacement", "d4/d80/interface_r_t_s_engine_1_1_building_extension_1_1_i_building_placement.html", "d4/d80/interface_r_t_s_engine_1_1_building_extension_1_1_i_building_placement" ],
    [ "IBuildingPlacementHandler", "d0/d22/interface_r_t_s_engine_1_1_building_extension_1_1_i_building_placement_handler.html", "d0/d22/interface_r_t_s_engine_1_1_building_extension_1_1_i_building_placement_handler" ],
    [ "IBuildingPlacementTask", "d2/ddf/interface_r_t_s_engine_1_1_building_extension_1_1_i_building_placement_task.html", "d2/ddf/interface_r_t_s_engine_1_1_building_extension_1_1_i_building_placement_task" ],
    [ "IBuildingPlacer", "d1/d40/interface_r_t_s_engine_1_1_building_extension_1_1_i_building_placer.html", "d1/d40/interface_r_t_s_engine_1_1_building_extension_1_1_i_building_placer" ],
    [ "IBuildingPlacerCondition", "da/db3/interface_r_t_s_engine_1_1_building_extension_1_1_i_building_placer_condition.html", "da/db3/interface_r_t_s_engine_1_1_building_extension_1_1_i_building_placer_condition" ],
    [ "IGridPlacementHandler", "d6/d58/interface_r_t_s_engine_1_1_building_extension_1_1_i_grid_placement_handler.html", "d6/d58/interface_r_t_s_engine_1_1_building_extension_1_1_i_grid_placement_handler" ],
    [ "IGridPlacementMesh", "df/dec/interface_r_t_s_engine_1_1_building_extension_1_1_i_grid_placement_mesh.html", "df/dec/interface_r_t_s_engine_1_1_building_extension_1_1_i_grid_placement_mesh" ],
    [ "IPendingPlacementData", "de/d6e/interface_r_t_s_engine_1_1_building_extension_1_1_i_pending_placement_data.html", "de/d6e/interface_r_t_s_engine_1_1_building_extension_1_1_i_pending_placement_data" ],
    [ "LocalFactionPlacementHandler", "da/d38/class_r_t_s_engine_1_1_building_extension_1_1_local_faction_placement_handler.html", "da/d38/class_r_t_s_engine_1_1_building_extension_1_1_local_faction_placement_handler" ],
    [ "LocalGridPlacementMesh", "d4/dbb/class_r_t_s_engine_1_1_building_extension_1_1_local_grid_placement_mesh.html", "d4/dbb/class_r_t_s_engine_1_1_building_extension_1_1_local_grid_placement_mesh" ],
    [ "PendingPlacementData", "d2/df0/struct_r_t_s_engine_1_1_building_extension_1_1_pending_placement_data.html", "d2/df0/struct_r_t_s_engine_1_1_building_extension_1_1_pending_placement_data" ],
    [ "PlacementGridCell", "d8/dd6/class_r_t_s_engine_1_1_building_extension_1_1_placement_grid_cell.html", "d8/dd6/class_r_t_s_engine_1_1_building_extension_1_1_placement_grid_cell" ],
    [ "ConstructionType", "d7/da7/namespace_r_t_s_engine_1_1_building_extension.html#a82956cd4157adb1fe21740498c8ebb53", [
      [ "health", "d7/da7/namespace_r_t_s_engine_1_1_building_extension.html#a82956cd4157adb1fe21740498c8ebb53a555bf8344ca0caf09b42f55e185526d8", null ],
      [ "time", "d7/da7/namespace_r_t_s_engine_1_1_building_extension.html#a82956cd4157adb1fe21740498c8ebb53a07cc694b9b3fc636710fa08b6922c42b", null ]
    ] ],
    [ "GridAreaPivotPoint", "d7/da7/namespace_r_t_s_engine_1_1_building_extension.html#aa5965fe02cd6f393f113e49aee35279a", [
      [ "center", "d7/da7/namespace_r_t_s_engine_1_1_building_extension.html#aa5965fe02cd6f393f113e49aee35279aaadb115059e28d960fa8badfac5516667", null ],
      [ "topLeft", "d7/da7/namespace_r_t_s_engine_1_1_building_extension.html#aa5965fe02cd6f393f113e49aee35279aa79ad18f72445fe00af22637f175bf878", null ],
      [ "bottomLeft", "d7/da7/namespace_r_t_s_engine_1_1_building_extension.html#aa5965fe02cd6f393f113e49aee35279aa5d42a1b01d408cdd65bb03d50fa0dd22", null ],
      [ "topRight", "d7/da7/namespace_r_t_s_engine_1_1_building_extension.html#aa5965fe02cd6f393f113e49aee35279aa3dc32cc133f011c0f50bca1a9b09e7a1", null ],
      [ "bottomRight", "d7/da7/namespace_r_t_s_engine_1_1_building_extension.html#aa5965fe02cd6f393f113e49aee35279aa83da849839b8af951893682450a363a1", null ]
    ] ]
];