var namespace_r_t_s_engine_1_1_event =
[
    [ "AttackLaunchEventArgs", "da/d5a/class_r_t_s_engine_1_1_event_1_1_attack_launch_event_args.html", "da/d5a/class_r_t_s_engine_1_1_event_1_1_attack_launch_event_args" ],
    [ "BorderEventArgs", "d7/d2f/class_r_t_s_engine_1_1_event_1_1_border_event_args.html", "d7/d2f/class_r_t_s_engine_1_1_event_1_1_border_event_args" ],
    [ "DeadEventArgs", "d2/dfc/class_r_t_s_engine_1_1_event_1_1_dead_event_args.html", "d2/dfc/class_r_t_s_engine_1_1_event_1_1_dead_event_args" ],
    [ "DefeatConditionEventArgs", "df/d97/class_r_t_s_engine_1_1_event_1_1_defeat_condition_event_args.html", "df/d97/class_r_t_s_engine_1_1_event_1_1_defeat_condition_event_args" ],
    [ "EntityComponentEventArgs", "d4/ddd/class_r_t_s_engine_1_1_event_1_1_entity_component_event_args.html", "d4/ddd/class_r_t_s_engine_1_1_event_1_1_entity_component_event_args" ],
    [ "EntityComponentUpgradeEventArgs", "d6/dc4/class_r_t_s_engine_1_1_event_1_1_entity_component_upgrade_event_args.html", "d6/dc4/class_r_t_s_engine_1_1_event_1_1_entity_component_upgrade_event_args" ],
    [ "EntityDeselectionEventArgs", "df/d20/class_r_t_s_engine_1_1_event_1_1_entity_deselection_event_args.html", "df/d20/class_r_t_s_engine_1_1_event_1_1_entity_deselection_event_args" ],
    [ "EntityEventArgs", "d5/da0/class_r_t_s_engine_1_1_event_1_1_entity_event_args.html", "d5/da0/class_r_t_s_engine_1_1_event_1_1_entity_event_args" ],
    [ "EntitySelectionEventArgs", "d6/d7f/class_r_t_s_engine_1_1_event_1_1_entity_selection_event_args.html", "d6/d7f/class_r_t_s_engine_1_1_event_1_1_entity_selection_event_args" ],
    [ "FactionUpdateArgs", "d4/d88/class_r_t_s_engine_1_1_event_1_1_faction_update_args.html", "d4/d88/class_r_t_s_engine_1_1_event_1_1_faction_update_args" ],
    [ "GlobalEventPublisher", "de/d10/class_r_t_s_engine_1_1_event_1_1_global_event_publisher.html", "de/d10/class_r_t_s_engine_1_1_event_1_1_global_event_publisher" ],
    [ "HealthUpdateArgs", "d2/d1c/struct_r_t_s_engine_1_1_event_1_1_health_update_args.html", "d2/d1c/struct_r_t_s_engine_1_1_event_1_1_health_update_args" ],
    [ "IGlobalEventPublisher", "d9/dd7/interface_r_t_s_engine_1_1_event_1_1_i_global_event_publisher.html", "d9/dd7/interface_r_t_s_engine_1_1_event_1_1_i_global_event_publisher" ],
    [ "MessageEventArgs", "d3/d39/struct_r_t_s_engine_1_1_event_1_1_message_event_args.html", "d3/d39/struct_r_t_s_engine_1_1_event_1_1_message_event_args" ],
    [ "MovementEventArgs", "d4/d17/struct_r_t_s_engine_1_1_event_1_1_movement_event_args.html", "d4/d17/struct_r_t_s_engine_1_1_event_1_1_movement_event_args" ],
    [ "PendingTaskEventArgs", "d8/d60/struct_r_t_s_engine_1_1_event_1_1_pending_task_event_args.html", "d8/d60/struct_r_t_s_engine_1_1_event_1_1_pending_task_event_args" ],
    [ "ResourceAmountEventArgs", "d8/d69/class_r_t_s_engine_1_1_event_1_1_resource_amount_event_args.html", "d8/d69/class_r_t_s_engine_1_1_event_1_1_resource_amount_event_args" ],
    [ "ResourceEventArgs", "da/dbd/struct_r_t_s_engine_1_1_event_1_1_resource_event_args.html", "da/dbd/struct_r_t_s_engine_1_1_event_1_1_resource_event_args" ],
    [ "ResourceUpdateEventArgs", "d5/d2f/class_r_t_s_engine_1_1_event_1_1_resource_update_event_args.html", "d5/d2f/class_r_t_s_engine_1_1_event_1_1_resource_update_event_args" ],
    [ "TargetDataEventArgs", "d5/dce/struct_r_t_s_engine_1_1_event_1_1_target_data_event_args.html", "d5/dce/struct_r_t_s_engine_1_1_event_1_1_target_data_event_args" ],
    [ "TaskUIReloadEventArgs", "d2/d83/class_r_t_s_engine_1_1_event_1_1_task_u_i_reload_event_args.html", "d2/d83/class_r_t_s_engine_1_1_event_1_1_task_u_i_reload_event_args" ],
    [ "UnitCarrierEventArgs", "d6/d8f/class_r_t_s_engine_1_1_event_1_1_unit_carrier_event_args.html", "d6/d8f/class_r_t_s_engine_1_1_event_1_1_unit_carrier_event_args" ],
    [ "UpgradeEventArgs", "df/def/class_r_t_s_engine_1_1_event_1_1_upgrade_event_args.html", "df/def/class_r_t_s_engine_1_1_event_1_1_upgrade_event_args" ],
    [ "VisibilityEventArgs", "d1/d6e/class_r_t_s_engine_1_1_event_1_1_visibility_event_args.html", "d1/d6e/class_r_t_s_engine_1_1_event_1_1_visibility_event_args" ],
    [ "CustomEventHandler< T, E >", "d4/d40/namespace_r_t_s_engine_1_1_event.html#a0dd80d97fb970af9d48913bf93cb75ab", null ]
];